### ISSUE TITLE
Should we have some kind of lightweight caching mechanism?

### ISSUE THREAD

**Issue by timboisvert** [kilt-cms/kilt-cms#10]
Do we want to require memcache? Sounds oppressive. Perhaps we can find a way to cache the results of the database calls and invalidate them every x minutes or whenever any of the objects are changed. We need to think through this a bit.

**Comment by darrencauthon** [comment]
My opinion:  This is not necessary.  Two reasons:
1.  RethinkDB is already pretty fast, and I've never seen querying dbs like it (or Mongo) ever be a problem.
2.  Rails already has some easy-to-implement caching schemes... why not rely on them?

**Comment by timboisvert** [comment]
We came to the same conclusion internally. Rails' caching mechanisms are so easy to use that it makes way more sense to cache content after it comes out of kilt, not before. All of our production Kilt instances are running with Rails caching external to Kilt and it works great.

**Comment by timboisvert** [comment]
Closing.
