### ISSUE TITLE
Travis CI tests against DB

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#12]
Since this system relies on RethinkDB, any tests of the Rails features or Rethink-specific features will require a connection to RethinkDB.

I'm not sure if we can have environment variables that are privately held by Travis CI, but I haven't looked very hard.

**Comment by darrencauthon** [comment]
I think this can be handled in a few ways...
1. Find a way to handle this in TravisCI.  I'm sure there is a way, but I'm not sure how.
2.  Flag those tests dependent on RethinkDB to work only when a RethinkDB test database is present.  Oh... what tests dependent on RethinkDB?  The ones I'm writing now.
3. I've been working on a project called "CI in a Can".  I wrote it to run my own simple CI server.  We have apps that are dependent on a number of things... things that are super-easy to setup on my own Linux box, but not so easy with other CI systems.  So for most of my Ruby apps, I pay for a $5 Digital Ocean server running my own CI with my own setup.     https://github.com/darrencauthon/ci_in_a_can

So in this case, RethinkDB on a server and the CI could run through that server.  

All this said... I don't want to fill up the tickets with things that are not immediately actionable, so I suggest we table this for now.

**Comment by timboisvert** [comment]
Cool thoughts. Agree on tabling for now.

Tim
