### ISSUE TITLE
Set the "type" in the create method, not "fill"

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#17]
I tried using the Kilt.create method in an isolated test, independent of the KiltController.

I checked the results, and noticed that the "type" field wasn't being set.

![rethinkdb administration console](https://f.cloud.github.com/assets/148768/2410009/7c1e4e4c-aab8-11e3-977f-e23d276ff7fd.jpg)

Just through code review, it looks like type gets set in the Object's fill method:

https://github.com/AsheAvenue/Kilt/blob/29f0049bf579583926e91dd7405c26a4c512bf02/lib/kilt/object.rb#L35

Which is always called in the Kilt Controller here:

https://github.com/AsheAvenue/Kilt/blob/29f0049bf579583926e91dd7405c26a4c512bf02/app/controllers/kilt/kilt_controller.rb#L47

I'd suggest this be moved to the Kilt create method, say here:
  https://github.com/AsheAvenue/Kilt/blob/29f0049bf579583926e91dd7405c26a4c512bf02/lib/kilt.rb#L41

Which will guarantee that type is set whenever an object is created, no matter where it is created.

Easy change, but I'd prefer to do this after wrapping this behavior in tests.  Just give me a bit, and I'll submit a PR.

**Comment by timboisvert** [comment]
Awesome. Loving your work on this!

**Comment by darrencauthon** [comment]
This is resolved.
