### ISSUE TITLE
Remove frontend generator?

### ISSUE THREAD

**Issue by timboisvert** [kilt-cms/kilt-cms#36]
In hindsight, I haven't used it and doubt that I ever would. The main install generator just runs the backend generator. Not sure it's worth keeping the front-end generator. Thoughts?

**Comment by heathcliff** [comment]
I support this. I feel like Kilt's mission is to simplify the backend/CMS side of things, and not act as a front-end framework.

**Comment by darrencauthon** [comment]
Agreed!  I'd never use it, and I don't think most people would want it.  It could also create confusion for new devs.

Shouldn't be too hard to do it; I'll do it unless someone else wants the honor.  Because... removing code from a library **is** an honor.

**Comment by timboisvert** [comment]
Darren: I was going to do it, but now that you put it that way, I'd prefer you have the honor!

**Comment by darrencauthon** [comment]
:smile:  I'll do it.

**Comment by darrencauthon** [comment]
This was resolved when #41 was merged in.
