### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#37]
How about getting an logo for Kilt?

I've used fiverr.com in the past to get logos.  It might take a few tries, but at $5-$15 a pop it's not bad.

Here's a logo someone built for me for another project of mine, CI In A Can:

https://camo.githubusercontent.com/3a1fd6e42c4ce6b7c94ea6deb2d1a6d343332c93/68747470733a2f2f7261772e6769746875622e636f6d2f64617272656e63617574686f6e2f63695f696e5f615f63616e2f6d61737465722f6173736574732f736d616c6c6c6f676f2e706e67

Here's another logo, one I had made for the KC Ruby group:

https://github.com/darrencauthon/newkcruby/blob/master/logo.png

**Comment by timboisvert** [comment]
I think I'd prefer to just have a logotype with a tartan pattern somewhere on the page. I've got some designs we did before. Might revisit them in light of the new font work I did yesterday.

**Comment by timboisvert** [comment]
Another alternative I had in mind was to use a simple icon of bagpipes for the Kilt logo. Something from The Noun Project like: http://thenounproject.com/term/bagpipe/3481/

**Comment by darrencauthon** [comment]
Yeah, I like that.

Either is fine, it's just helpful to have some sort of non-text representation of the project.

**Comment by timboisvert** [comment]
I just tried a couple treatments with the bagpipe and it didn't really work, so I've got a Scottish Terrier icon that looks a lot better.

**Comment by timboisvert** [comment]
Here's the terrier I want to use: http://thenounproject.com/term/scottish-terrier/6257/

**Comment by darrencauthon** [comment]
Perfect!
