### ISSUE TITLE
Pop release 1.1

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#50]
It's easy, just pull latest master and:

```
bundle exec rake release
```

Oooooorrrrr you can give me rights to do it, I'm `darrencauthon` on rubygems.  https://rubygems.org/profiles/darrencauthon

@timboisvert

**Comment by timboisvert** [comment]
Happy to do it if you’re busy today. Just wanted to give you ownership.

Tim

**Comment by darrencauthon** [comment]
Thank you sir!  I see you just deployed, but I'll do it in the future as changes come in.

```
kilt-cms 1.1.0 built to pkg/kilt-cms-1.1.0.gem.
Tag v1.1.0 has already been created.
Pushed kilt-cms 1.1.0 to rubygems.org.
```
