### ISSUE TITLE
Consider not providing the default front-end page

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-cms#6]
When I installed Kilt, it created a front-side controller named the same as my application, along with an index view that explained how to use Kilt.  

When I run the initial Kilt generator/installer, I am prompted to override my layout/application and the application.js file.

Is that necessary?  The information on the page could be found in the readme file, and I bet most devs will already have their own approach to that default page -- especially when Kilt leaves it to the developers to decide how to create the front-end views for the objects they create.

My suggestion:  Kilt tries to stay as far out of the way of the front-end as possible, perhaps to the point that it could be installed into a Rails application that doesn't already have a CMS.  This would require that it "namespace" itself away from the application, staying away from standards like "application.*"

**Comment by timboisvert** [comment]
Good call. We have the backend generator and the frontend generator, each of which can be run separately, or combined via the "install" generator. Maybe we should rename the backend generator to "install" and still have the "frontend" generator for those who want it. 

Tim

**Comment by darrencauthon** [comment]
I tried building an app with only the back-end generator, but I could not get the app to work.  Now, I only tried once, I was bundle exec'ing to my local copy of the gem, and the Chiefs game was on, so I must say first that I could make a mistake.  

My suspicion before I did anything was that it wouldn't work, as it looks like the few assets for the backend are built using the front-end generator.

**Comment by darrencauthon** [comment]
Specifically, it appears that the backend generator has no assets...

https://github.com/AsheAvenue/Kilt/blob/6f8799a0d6133bdf9f3eee0929993df13e0c9eea/lib/generators/kilt/backend_generator.rb#L8

... which would make it dependent on the frontend generator here:

https://github.com/AsheAvenue/Kilt/blob/6f8799a0d6133bdf9f3eee0929993df13e0c9eea/lib/generators/kilt/frontend_generator.rb#L8
